# Generated by Django 6.0.4 on 2026-05-28 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_student_user_book_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='home.student'),
        ),
    ]
