# Generated by Django 6.0.4 on 2026-05-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_book_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='student',
        ),
        migrations.AddField(
            model_name='book',
            name='students',
            field=models.ManyToManyField(related_name='books', to='home.student'),
        ),
    ]
